### ISSUE TITLE
How to save setting?

### ISSUE THREAD

**Issue by kydex** [fraktalfan/TrayMenu#1]
Settings don't save. Select folder, colors, icon, add folder to autostart then exit.
Start again and setting are default while set folder again in "Select Folder".
I was Export settings in .reg file and merge it, no effect.
I don't understand how it works or its a bug?

**Comment by fraktalfan** [comment]
Settings are saved automatically for each folder. If you use a different folder, you must pass this folder as a command-line argument to TrayMenu.exe, e.g.: C:\bin\TrayMenu.exe "C:\MyFolder"
To automate this, use "Settings > Create chortcut" to create a shortcut and use this shortcut to start TrayMenu using your folder. Alternatively, use "Settings > Autostart" to start TrayMenu automatically with Windows using your folder.

**Comment by kydex** [comment]
"Settings > Autostart" don't work for me, but "Settings > Create shortcut" is working.
Thank you for this soft! I've been looking for something like this for a long time.
I have to learn how to work with "traymenu.ini", seems like its awesome.
